docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - { Introduction: intro.md }
    - { 'Installation and Usage': usage.md }
    - { 'Default Params': default-params.md }
site_name: phly-mustache
site_description: 'phly-expressive-mustache: phly-mustache template adapter for Expressive'
repo_url: 'https://github.com/phly/phly-mustache'
copyright: 'Copyright (c) 2015 <a href="https://mwop.net/">Matthew Weier O\''Phinney</a>'
